In [ ]:

faqs = """
The sun shone brightly overhead as Sarah stepped out of her house, breathing in the crisp morning air.
She had been looking forward to this day for weeks, ever since she had received the invitation in the mail.
Today was the day of the annual town fair, a tradition that brought the entire community together for a day of fun and festivities.
Sarah walked down the bustling street, taking in the sights and sounds of the fair as she made her way to the town square.
Colorful banners fluttered in the breeze, and the smell of cotton candy and popcorn filled the air.
Children laughed and played games, their faces painted with excitement.
As Sarah reached the town square, she spotted her friends gathered near the entrance to the fairgrounds.
They waved excitedly as she approached, their chatter filling the air with energy and anticipation.
Sarah smiled, feeling a sense of joy and camaraderie as she joined them.
Together, they entered the fairgrounds, eager to explore all the attractions the fair had to offer.
They wandered through rows of booths selling handmade crafts and delicious treats, stopping to admire the intricate artwork and sample tasty snacks along the way.
Suddenly, Sarah's stomach rumbled, reminding her that she hadn't eaten breakfast yet.
She scanned the area, searching for a food vendor selling her favorite fair food - funnel cakes.
Spotting a booth in the distance, she hurried over, her mouth watering at the thought of the warm, sugary goodness.
After indulging in a delicious funnel cake, Sarah and her friends continued their adventure, trying their luck at various games and rides.
They laughed and cheered each other on, reveling in the simple pleasures of the fair.
As the day wore on, the sun began to sink lower in the sky, casting a golden glow over the fairgrounds.
Sarah felt a sense of contentment wash over her as she watched the sun set, grateful for the memories she had made with her friends.
Eventually, the fair came to a close, and Sarah and her friends reluctantly made their way home, their memories of the day still fresh in their minds.
The streets were quiet now, the hustle and bustle of the fair replaced by the peacefulness of the evening.
As Sarah walked home, she reflected on the day's events, feeling a sense of happiness and fulfillment.
The fair had been everything she had hoped for and more, a day filled with laughter, friendship, and fun.
When she finally reached her house, Sarah paused for a moment to take in the quiet beauty of the night.
The stars twinkled overhead, casting a soft glow over the neighborhood.
It had been a perfect day, one she would always cherish in her heart.
As she stepped inside her house, Sarah couldn't help but smile.
She knew that she would always treasure the memories of this day, the day of the annual town fair.
And as she drifted off to sleep that night, she felt grateful for the simple joys that life had to offer.
The next morning, Sarah woke up with a lingering sense of excitement from the previous day's festivities.
She stretched lazily in bed, savoring the warmth of the morning sunlight streaming through her window.
Today was a new day, full of possibilities and adventures waiting to unfold.
After a leisurely breakfast, Sarah decided to take a stroll through the park near her house.
The park was a peaceful oasis in the midst of the bustling city, with towering trees and colorful flowers in bloom.
As she walked along the winding paths, Sarah felt a sense of serenity wash over her, the cares of the world melting away with each step.
As she wandered deeper into the park, Sarah stumbled upon a secluded pond, its surface shimmering in the sunlight.
Ducks paddled lazily in the water, their quacks echoing softly across the tranquil scene.
Sarah sat down on a nearby bench, taking in the beauty of her surroundings.
Lost in thought, Sarah spent the rest of the morning in quiet contemplation by the pond.
She watched as the sun climbed higher in the sky, casting dappled shadows on the water's surface.
Time seemed to stand still as she savored the peace and solitude of the moment.
Eventually, hunger pangs reminded Sarah that it was time for lunch.
She packed up her belongings and made her way to a nearby café, where she ordered a delicious sandwich and a steaming cup of coffee.
As she sat at a table by the window, she watched the world go by outside, feeling grateful for the simple pleasures of life.
After lunch, Sarah decided to spend the afternoon exploring the local bookstore.
She had always been an avid reader, and the prospect of discovering new books filled her with excitement.
As she perused the shelves, she lost herself in a world of stories and adventures, each book offering a new opportunity for escape and exploration.
As the afternoon waned, Sarah reluctantly left the bookstore, her arms laden with treasures to devour at home.
She walked back to her house, her heart light and her mind buzzing with ideas and inspiration.
The day had been filled with unexpected delights and serendipitous encounters, reminding her of the magic that could be found in the most ordinary of days.
That evening, as Sarah curled up on her couch with a book in hand, she couldn't help but smile.
Life was full of wonders, both big and small, and she was grateful for each and every moment.
As she turned the pages of her book, she knew that the adventures of the day were just the beginning of a lifetime of exploration and discovery.
With a contented sigh, Sarah settled in for the night, feeling grateful for the simple joys and pleasures that filled her days.
And as she drifted off to sleep, she knew that tomorrow would bring new adventures and new opportunities for joy and wonder.
The next day dawned bright and clear, promising another day of excitement and adventure for Sarah.
She woke up early, eager to make the most of the day ahead.
After a quick breakfast, she decided to head to the nearby hiking trail she had been meaning to explore for weeks.
The trail wound its way through dense forest, the earthy scent of pine and moss filling the air.
Birds chirped merrily overhead, their songs a cheerful accompaniment to Sarah's footsteps.
As she hiked deeper into the woods, she felt a sense of peace and tranquility settle over her, the worries of the world fading into the background.
Along the way, Sarah encountered several fellow hikers, exchanging friendly greetings and sharing tales of their outdoor adventures.
She paused at a scenic overlook to take in the breathtaking views of the valley below, marveling at the beauty of the natural world.
As she continued her hike, Sarah stumbled upon a hidden waterfall tucked away in a secluded corner of the forest.
The sound of rushing water filled the air as she approached, the spray from the falls cooling her skin.
She sat down on a nearby rock, mesmerized by the cascading water and the beauty of the scene before her.
Lost in the moment, Sarah spent the rest of the morning exploring the area around the waterfall, snapping photos and soaking in the tranquility of her surroundings.
She felt a sense of connection to nature unlike anything she had ever experienced before, grateful for the opportunity to immerse herself in its wonders.
Eventually, hunger called Sarah back to reality, and she reluctantly made her way back to the trailhead.
As she walked, she couldn't help but smile, feeling refreshed and invigorated by her time in the wilderness.
Back home, Sarah decided to spend the afternoon pursuing one of her favorite hobbies - gardening.
She donned her gardening gloves and set to work tending to her flower beds, carefully planting new blooms and pruning back overgrown foliage.
As she worked, Sarah felt a sense of satisfaction wash over her, the rhythmic motions of gardening calming her mind and soothing her soul.
She lost track of time as she immersed herself in the task at hand, the worries of the world fading away with each weed she pulled and each flower she planted.
By the time evening rolled around, Sarah's garden was transformed into a colorful oasis of blooms and greenery.
She stepped back to admire her handiwork, feeling a sense of pride in what she had accomplished.
As the sun dipped below the horizon, she settled into a chair on her porch, content to bask in the beauty of her garden and the peace of the evening.
As she sat there, watching the stars twinkle into life overhead, Sarah couldn't help but feel grateful for the simple joys of life - the beauty of nature, the satisfaction of hard work, and the peace of a quiet evening at home.
And as she drifted off to sleep that night, she knew that no matter what tomorrow brought, she would face it with a heart full of gratitude and a spirit full of adventure.
"""


import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer


In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([faqs])
tokenizer.word_index

{'the': 1,
 'of': 2,
 'she': 3,
 'and': 4,
 'a': 5,
 'her': 6,
 'to': 7,
 'in': 8,
 'as': 9,
 'sarah': 10,
 'for': 11,
 'day': 12,
 'with': 13,
 'had': 14,
 'that': 15,
 'their': 16,
 'fair': 17,
 'sense': 18,
 'at': 19,
 'on': 20,
 'was': 21,
 'way': 22,
 'over': 23,
 'grateful': 24,
 'by': 25,
 'been': 26,
 'filled': 27,
 'feeling': 28,
 'each': 29,
 'felt': 30,
 'beauty': 31,
 'new': 32,
 'world': 33,
 'into': 34,
 'back': 35,
 'sun': 36,
 'house': 37,
 'morning': 38,
 'air': 39,
 'walked': 40,
 'made': 41,
 'simple': 42,
 'home': 43,
 'evening': 44,
 'life': 45,
 'adventures': 46,
 'time': 47,
 'overhead': 48,
 'town': 49,
 'excitement': 50,
 'friends': 51,
 'they': 52,
 'through': 53,
 'after': 54,
 'quiet': 55,
 'moment': 56,
 'night': 57,
 'would': 58,
 "couldn't": 59,
 'help': 60,
 'but': 61,
 'knew': 62,
 'up': 63,
 'full': 64,
 'decided': 65,
 'sat': 66,
 'nearby': 67,
 'lost': 68,
 'peace': 69,
 'stepped': 70,
 'down': 71,
 'colorful': 72,
 'fairgrounds': 73,
 'delicious': 7

In [ ]:
input_sequences = []
for sentence in faqs.split('\n'):
  # print(sentence)
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
  for i in range(1, len(tokenized_sentence)):
    n_gram = tokenized_sentence[:i+1]
    input_sequences.append(n_gram)

In [ ]:
max_len = max([len(x) for x in input_sequences])
print(max_len)

41


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences


padded_input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')

In [ ]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,   1,  36],
       [  0,   0,   0, ...,   1,  36, 191],
       [  0,   0,   0, ...,  36, 191, 192],
       ...,
       [  0,   0,   0, ...,   5, 530,  64],
       [  0,   0,   0, ..., 530,  64,   2],
       [  0,   0,   0, ...,  64,   2,  78]], dtype=int32)

In [ ]:
x = padded_input_sequences[:, :-1]

In [ ]:
y = padded_input_sequences[:, -1]

In [ ]:
print(x)

[[  0   0   0 ...   0   0   1]
 [  0   0   0 ...   0   1  36]
 [  0   0   0 ...   1  36 191]
 ...
 [  0   0   0 ...   4   5 530]
 [  0   0   0 ...   5 530  64]
 [  0   0   0 ... 530  64   2]]


In [ ]:
print(y)

[ 36 191 192 ...  64   2  78]


In [ ]:
x.shape

(1445, 40)

In [ ]:
y.shape

(1445,)

In [ ]:
from tensorflow.keras.utils import to_categorical
total_unique_words = len(tokenizer.word_index)
print(total_unique_words)
# tokenizer.word_index will be starting from 1 onwards whereas onehot encoding is from 0
y = to_categorical(y, num_classes=total_unique_words+1)


530


In [ ]:
y.shape
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# Now our Data is ready :)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = Sequential()
model.add(Embedding(total_unique_words+1, 100, input_length=max_len-1))
model.add(LSTM(150))
model.add(Dense(total_unique_words+1, activation='softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 40, 100)           53100     
                                                                 
 lstm_2 (LSTM)               (None, 150)               150600    
                                                                 
 dense_2 (Dense)             (None, 531)               80181     
                                                                 
Total params: 283881 (1.08 MB)
Trainable params: 283881 (1.08 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [48]:
model.fit(x, y, epochs=100)

Epoch 1/100
46/46 [==============================] - 5s 107ms/step - loss: 0.1415 - accuracy: 0.9550
Epoch 2/100
46/46 [==============================] - 3s 74ms/step - loss: 0.1417 - accuracy: 0.9592
Epoch 3/100
46/46 [==============================] - 4s 79ms/step - loss: 0.1409 - accuracy: 0.9571
Epoch 4/100
46/46 [==============================] - 6s 128ms/step - loss: 0.1378 - accuracy: 0.9571
Epoch 5/100
46/46 [==============================] - 4s 97ms/step - loss: 0.1387 - accuracy: 0.9557
Epoch 6/100
46/46 [==============================] - 3s 69ms/step - loss: 0.1340 - accuracy: 0.9578
Epoch 7/100
46/46 [==============================] - 4s 90ms/step - loss: 0.1335 - accuracy: 0.9543
Epoch 8/100
46/46 [==============================] - 4s 82ms/step - loss: 0.1323 - accuracy: 0.9578
Epoch 9/100
46/46 [==============================] - 3s 71ms/step - loss: 0.1325 - accuracy: 0.9557
Epoch 10/100
46/46 [==============================] - 3s 71ms/step - loss: 0.1324 - accuracy: 0.95

In [50]:
import numpy as np

text = "sun"

for i in range(5):

  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]

  # padding
  padded_token_text = pad_sequences([token_text], maxlen=max_len-1, padding='pre')
  # print(padded_token_text)

  # prediction
  # model.predict(padded_token_text).shape
  model.predict(padded_token_text)


  position = np.argmax(model.predict(padded_token_text))

  for word, index in tokenizer.word_index.items():
    if index == position:
      text = text + " " + word
      print(text)


1/1 [==============================] - 0s 27ms/step
sun wandered
1/1 [==============================] - 0s 26ms/step
sun wandered through
1/1 [==============================] - 0s 27ms/step
sun wandered through rows
1/1 [==============================] - 0s 27ms/step
sun wandered through rows of
1/1 [==============================] - 0s 26ms/step
sun wandered through rows of booths
